apiVersion: apps/v1
kind: Deployment
metadata:
  name: syndicator-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: syndicator-api
  template:
    metadata:
      labels:
        app: syndicator-api
    spec:
      containers:
      - image: 'ghcr.io/sharph/syndicator-api:{{ .Values.api.image.tag }}'
        name: syndicator-api
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: username
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: port
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: dbname
        - name: DJANGO_ALLOWED_HOSTS
          value: '["{{ .Values.api.domain }}"]'
        - name: DJANGO_DEBUG
          value: "false"
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: syndicator-app
              key: django-secret
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
        # startupProbe:
        #   httpGet:
        #     path: /ht/
        #     port: 8000
        #     httpHeaders:
        #     - name: Host
        #       value: "{{ .Values.api.domain }}"
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 10
        # livenessProbe:
        #   httpGet:
        #     path: /ht/
        #     port: 8000
        #     httpHeaders:
        #     - name: Host
        #       value: "{{ .Values.api.domain }}"
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ht/
        #     port: 8000
        #     httpHeaders:
        #     - name: Host
        #       value: "{{ .Values.api.domain }}"
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: syndicator-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: syndicator-api