apiVersion: apps/v1
kind: Deployment
metadata:
  name: syndicator-fetcher
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: syndicator-fetcher
  template:
    metadata:
      labels:
        app: syndicator-fetcher
    spec:
      containers:
      - image: 'ghcr.io/sharph/syndicator-api:{{ .Values.updater.image.tag }}'
        name: phlparty
        command: ["./manage.py", "fetchfeeds"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: username
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: port
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: syndicator-database-app
              key: dbname
        - name: DJANGO_ALLOWED_HOSTS
          value: '["{{ .Values.api.domain }}"]'
        - name: DJANGO_DEBUG
          value: "false"
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: syndicator-app
              key: django-secret
        resources:
          limits:
            memory: 512Mi
            cpu: 250m